name: default
inputs:
    TestConfig.host:
        text: 143.198.64.230
    TestConfig.key:
        secret: ENC[AES256_GCM,data:ewAmTZ7rBhcnl+Gq/OtDHepSypeSWcJU7D2KURc8usPLetdzFB7+3XTgLWmrKS/CUdHdTY1ND2CtviekLZOgfZpOEy1WpyJsVOukivTOcZOH474EguEd8LD9Ka91CiYuyv5gCKQX5QKG1OZ8tS81Nmou7o2gM9J++1HK2YzlPSUUglY5v0oeV+TQNRzSbim+5Xis7W8UoBBZKmw6hbVbyaCJl0eHhpRiBZuOH7/Q2nPwkdAmh75O35V/aBrrfUFNp5CT4OdyR/IrfnzY+Du9v+GpkRnCILFCiHJzd1as5ueVXmCbydNtVTWzhDnkQzJj9q780z9W/2YFMOp6I/cpHNlxBq9gXC3ogcHM34N6VcbVHC9gSHGNcOufuDUOXimbgboLNta9Icosj7GQNAq8hTbV0mbS6P+fYtUnDQMo177pjRPAHVNXpkQnuXb0jhPi2+MgdaywbXydcmD8F/WsWzqRxi3piL+W9QRn3+CzpI/z00svzJPUI6bRuC7gkfJUjUnyOyP+x5RMXzA8aoj1ufHzZS/nB3XesUS/,iv:gfYm2yjbr4IrAoRhPS9jbn2HwfQEhos2Xz4ghNkb0/k=,tag:lUGS4KBVczyzwu+Hp3ehXw==,type:str]
    TestConfig.user:
        text: root
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpamtuNHB6NjY5L3VNT3hl
            TGlmVFFoZURJR1RmZEFvSGUyVFRaSWNnSUMwClJiaDVGZWJoeDBMY21jZTVlREdS
            aWg0SjNWN3BrTXRneXJyZy80K1JRSFUKLS0tIFEwKzdkVkNPT2VHTmtiOEdDQlZa
            cnh2eHU5TzFjVkNvTzUyczFBL0pwTDQK60+wrLmTaD3Ws5ZAXdqBkMjaVP7Iz69k
            UrkqkMbaUlvvSKK7dB5MuTGEEN6A1viAGal9ZjDHlSobkNPuE24QEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-07T21:46:00Z"
    mac: ENC[AES256_GCM,data:hmw4ffQL+8lcDdevuJFy0lWD4ItISg2XxFCxNqaYhEOBneEkWQLJmrzX35yp3PoMvgDGLCFNFWamKEgU7WkXe9v4h19UmtOBJLRvj2USDguRBNUBMIiEyijwUbp+Eur28U7V3yWfeltCuBMw+woui9waQeG3PbDkoKUyBztuhS8=,iv:9vno6+T8SHeCiGIN+z95a8lKFaFzV0jimrAbsPQSmrc=,tag:uaN4MGeksUSCasaMyitFJQ==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
