name: docker-run-local
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpamtuNHB6NjY5L3VNT3hl
            TGlmVFFoZURJR1RmZEFvSGUyVFRaSWNnSUMwClJiaDVGZWJoeDBMY21jZTVlREdS
            aWg0SjNWN3BrTXRneXJyZy80K1JRSFUKLS0tIFEwKzdkVkNPT2VHTmtiOEdDQlZa
            cnh2eHU5TzFjVkNvTzUyczFBL0pwTDQK60+wrLmTaD3Ws5ZAXdqBkMjaVP7Iz69k
            UrkqkMbaUlvvSKK7dB5MuTGEEN6A1viAGal9ZjDHlSobkNPuE24QEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-09T19:32:39Z"
    mac: ENC[AES256_GCM,data:Sm+KP6fL5SVpYxQ03978TAnMI4yqNHQomt2uQA23q+3YN+K7okVS7CM+By/K8Xn2Z3y26A4hFnRvMJTV/qpGQ4hz9+qWU5AOuQvJqtNvRgkf6yfFhF6nWS3vNIHbKdHHD8cBXWGvU+A/j/3YsjJL2GlLd1Tcee9WbmKKBKEDSpg=,iv:0pmOoiyZybpS4kdmjQaTueU5wrMMuDh1qMQrcI4yeXI=,tag:p3y0cMY0h1b/p35snTZ6rg==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
