name: aws-s3
inputs:
    TestConfig.awsConfig.accessKey:
        secret: ENC[AES256_GCM,data:iu6LfQNgGZUVnHVeMRYPrcBtlZk=,iv:U5PLxDKXwJnUDdk1ayFGvvJfWdVqh1PK5ujb20YYPP0=,tag:QyqIJRiR6nE16ZDV0CP7Pw==,type:str]
    TestConfig.awsConfig.secretKey:
        secret: ENC[AES256_GCM,data:Q/W+KH3NEouGt6C5S+KiC43837soYi2Mjb/z5K8rD9gtaNaBjjkJHg==,iv:8nGEzLXd91rF5YBZ/EdQoMN27yrpc0sgm26DEvIuSHM=,tag:/oyKl/vj5MJAm+jZMOOAuQ==,type:str]
    TestDirectory:
        dir:
            path: ./aws/s3/testdata
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeEk5MS9nVmFoOVNNOHdE
            WnZCTXBWbW9LL1NJYndCYjhIM2JsNXNEUmxJCkUya0dlZjZ0dGRIM1pVdzg5eWFH
            MVpiaE9PclNudGdUZm5FcytuVDZGTDAKLS0tIEQxWDdteHgzS3JkdmtNTVpxMUh1
            aXlvVWJVSGNTSkVyYmpZbi9nUVJZdmMK6csXZ2RMxFw5DB+Hb2TyhyoZT8c2/z7Y
            Lc9Pe8gb8aUq5Ha+wCybYvY6JWEM5A9XYJKbE7f4borTfGKS72d6pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-09T19:30:57Z"
    mac: ENC[AES256_GCM,data:kIT54J5QImmFYIgQvj6kDkWLa+7kWNN5yhN+A+2qwofJsLdbIrPrihd59mi+RPlRgO0gzePEqEsGfoNpQBMvfXZDAPDiHAv0xKiGLnkQLX1N9PxoSNvORzqk3SAHJPlfVIbVAmGEp4Oy09I0Qi43xvvISsYXtlsiMp0Zm/QfYFY=,iv:l902awO6UvpJIPogIKeOfsMgGL2Ivp4KFQ/1jef/+kU=,tag:yP0oPIwfReNU4gCIeUTwaQ==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
